### ISSUE TITLE
创建或更新实体之后会写入缓存吗？是否存在一致性问题？

### ISSUE THREAD

**Issue by TeslaCN** [jovezhao/nest#1]
阅读源码后的个人理解：
工作单元提交之后，会将变更提交到缓存中，数据库、缓存双写。

**在并发情况下，此处的逻辑是否有可能会产生一致性问题？**

https://github.com/jovezhao/nest/blob/ab1ed3e413a86d70c465442fdf33b1225bbca760/nest-ddd/src/main/java/com/zhaofujun/nest/context/ContextUnitOfWork.java#L108-L114
https://github.com/jovezhao/nest/blob/ab1ed3e413a86d70c465442fdf33b1225bbca760/nest-ddd/src/main/java/com/zhaofujun/nest/context/ContextUnitOfWork.java#L131-L147

**Comment by Ratsea** [comment]
不会哈~ 这个获取的上下文是通过线程副本进行获取的~ 所以不会有一致性的问题

**Comment by Ratsea** [comment]
> 
> 
> 阅读源码后的个人理解：
> 工作单元提交之后，会将变更提交到缓存中，数据库、缓存双写。
> 
> **在并发情况下，此处的逻辑是否有可能会产生一致性问题？**
> 
> https://github.com/jovezhao/nest/blob/ab1ed3e413a86d70c465442fdf33b1225bbca760/nest-ddd/src/main/java/com/zhaofujun/nest/context/ContextUnitOfWork.java#L108-L114
> 
> https://github.com/jovezhao/nest/blob/ab1ed3e413a86d70c465442fdf33b1225bbca760/nest-ddd/src/main/java/com/zhaofujun/nest/context/ContextUnitOfWork.java#L131-L147

**Comment by Ratsea** [comment]
> 
> 
> 阅读源码后的个人理解：
> 工作单元提交之后，会将变更提交到缓存中，数据库、缓存双写。
> 
> **在并发情况下，此处的逻辑是否有可能会产生一致性问题？**
> 
> https://github.com/jovezhao/nest/blob/ab1ed3e413a86d70c465442fdf33b1225bbca760/nest-ddd/src/main/java/com/zhaofujun/nest/context/ContextUnitOfWork.java#L108-L114
> 
> https://github.com/jovezhao/nest/blob/ab1ed3e413a86d70c465442fdf33b1225bbca760/nest-ddd/src/main/java/com/zhaofujun/nest/context/ContextUnitOfWork.java#L131-L147

ServiceContext serviceContext = ServiceContext.getCurrent(); 
该服务上下文是通过线程副本 TransmittableThreadLocal 进行获取的，并不会在高并发下出现一致性问题，除非你线程ID一致

**Comment by jovezhao** [comment]
可以考虑加入乐观锁来防止一致性问题，在仓储上加入version

**Comment by TeslaCN** [comment]
在写数据库的时候使缓存失效，在load的时候再将实体放入缓存，避免双写，实现起来会不会更简单？
